<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" VersionOverride="6.0.2" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" VersionOverride="17.12.0" />
    <PackageReference Include="xunit" VersionOverride="2.9.2" />
    <PackageReference Include="xunit.runner.visualstudio" VersionOverride="2.8.2" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FrameStudio.Avalonia\FrameStudio.Avalonia.csproj" />
    <ProjectReference Include="..\FrameStudio.Core\FrameStudio.Core.csproj" />
    <ProjectReference Include="..\FrameStudio.Platform.Abstractions\FrameStudio.Platform.Abstractions.csproj" />
    <ProjectReference Include="..\FrameStudio.Platform.Windows\FrameStudio.Platform.Windows.csproj" />
  </ItemGroup>

</Project>
